version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - '3006:3006'
    volumes: 
      - ./frontend:/app
    depends_on:
      - backend

  backend:
    build: 
      context: ./backend
    ports:
      - '5000:5000'
    volumes: 
      - ./backend:/app
  

